Repository SlamTalk/slam-talk-backend, pull requests merged in 2024-04, with the labels that each got.

#271 #241 chat 패키지 코드 리팩토링
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/ErrorMessage.java
  src/main/java/sync/slamtalk/chat/config/GenericMessage.java
  src/main/java/sync/slamtalk/chat/config/Message.java
  src/main/java/sync/slamtalk/chat/config/RoomCode.java
  src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java
  src/main/java/sync/slamtalk/chat/config/StompHandler.java
  src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java
  src/main/java/sync/slamtalk/chat/config/WebsocketDisconnectHandlerDecorator.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/dto/request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/dto/request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/dto/response/ChatUserDTO.java
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/Messages.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/redis/RedisConfig.java
  src/main/java/sync/slamtalk/chat/redis/RedisController.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/test/java/sync/slamtalk/chat/repository/MessagesRepositoryTest.java
Labels: 🛠️ Refactor

#288 Develop -> main 반영
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/ErrorMessage.java
  src/main/java/sync/slamtalk/chat/config/GenericMessage.java
  src/main/java/sync/slamtalk/chat/config/Message.java
  src/main/java/sync/slamtalk/chat/config/RoomCode.java
  src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java
  src/main/java/sync/slamtalk/chat/config/StompHandler.java
  src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java
  src/main/java/sync/slamtalk/chat/config/WebsocketDisconnectHandlerDecorator.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/dto/request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/dto/request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/dto/response/ChatUserDTO.java
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/Messages.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/redis/RedisConfig.java
  src/main/java/sync/slamtalk/chat/redis/RedisController.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/mate/dto/MateSearchCondition.java
  src/main/java/sync/slamtalk/mate/repository/QueryRepository.java
  src/test/java/sync/slamtalk/chat/repository/MessagesRepositoryTest.java
Labels: 🌏 Deploy

#290 refactor : 페이징 정렬순서 변경 DESC->ASC
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
Labels: 🛠️ Refactor

#291 Develop->main
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
Labels: 🌏 Deploy

#293 bug : ChatErrorResponseCode 메소드 수정,과거 내역 추가 요청 컨트롤러/서비스코드 수정
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#295 Develop -> main merge
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🌏 Deploy

#277 #266 SMTP 이메일 인증 전송 Thymeleaf 도입으로 HTML 양식으로 리팩터링
  build.gradle
  src/main/java/sync/slamtalk/email/EmailService.java
  src/main/resources/templates/register-email-verification-template.html
Labels: 🛠️ Refactor

#299 Bug/298 채팅방 입장 후 메세지 버그 수정
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#300 Develop->main
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🌏 Deploy

#284 280 user package 리팩터링
  src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/sync/slamtalk/security/oauth2/service/NicknameService.java
  src/main/java/sync/slamtalk/security/utils/CookieUtil.java
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/request/UpdateUserDetailInfoReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserSignUpReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserUpdatePositionAndSkillReq.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsMyInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserSchedule.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/entity/UserAttendance.java
  src/main/java/sync/slamtalk/user/entity/UserBasketballPositionType.java
  src/main/java/sync/slamtalk/user/entity/UserBasketballSkillLevelType.java
  src/main/java/sync/slamtalk/user/entity/UserRole.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/RevokeService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/main/java/sync/slamtalk/user/utils/UserDefaultImageUrls.java
  src/main/java/sync/slamtalk/user/utils/UserLevelScore.java
  src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java
  src/test/java/sync/slamtalk/security/oauth2/service/NicknameServiceTest.java
  src/test/java/sync/slamtalk/user/repository/UserRepositoryTest.java
  src/test/java/sync/slamtalk/user/service/UserServiceTest.java
Labels: 🛠️ Refactor

#302 Feature/301 chat 채팅리스트에서 최신 메세지부터 채팅방 정렬
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: ✨ Feature

#303 Develop->main
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/sync/slamtalk/security/oauth2/service/NicknameService.java
  src/main/java/sync/slamtalk/security/utils/CookieUtil.java
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/request/UpdateUserDetailInfoReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserSignUpReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserUpdatePositionAndSkillReq.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsMyInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserSchedule.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/entity/UserAttendance.java
  src/main/java/sync/slamtalk/user/entity/UserBasketballPositionType.java
  src/main/java/sync/slamtalk/user/entity/UserBasketballSkillLevelType.java
  src/main/java/sync/slamtalk/user/entity/UserRole.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/RevokeService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/main/java/sync/slamtalk/user/utils/UserDefaultImageUrls.java
  src/main/java/sync/slamtalk/user/utils/UserLevelScore.java
  src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java
  src/test/java/sync/slamtalk/security/oauth2/service/NicknameServiceTest.java
  src/test/java/sync/slamtalk/user/repository/UserRepositoryTest.java
  src/test/java/sync/slamtalk/user/service/UserServiceTest.java
Labels: 🌏 Deploy

#304 Bug/301 chatList 정렬수정
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#305 Develop->main
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🌏 Deploy
