Repository SlamTalk/slam-talk-backend, pull requests merged in 2024-02, with the labels that each got.

#103 #99 user 닉네임 검증 로직 추가/ 중복 방지 자동 생성 service 개발/ 닉네임 변경 api 개발 /최초 로그인 정보 수집 api 개발
  src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/sync/slamtalk/security/oauth2/service/NicknameService.java
  src/main/java/sync/slamtalk/user/UserRepository.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/UserLoginResponseDto.java
  src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
  src/main/java/sync/slamtalk/user/dto/UserUpdateNicknameRequestDto.java
  src/main/java/sync/slamtalk/user/dto/UserUpdatePositionAndSkillRequestDto.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/test/java/sync/slamtalk/security/oauth2/service/NicknameServiceTest.java
Labels: ✨ Feature

#105 #104 농구장 테이블 제보자ID 필드 추가 & 제보자 id 저장
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: 🛠️ Refactor, ✨ Feature

#106 #95 팀매칭 신청자 엔티티, 계층구조 생성 및 팀매칭 목록 구현
  src/main/java/sync/slamtalk/mate/controller/ParticipantController.java
  src/main/java/sync/slamtalk/mate/entity/ApplyStatusType.java
  src/main/java/sync/slamtalk/mate/entity/MatePost.java
  src/main/java/sync/slamtalk/mate/entity/RecruitmentStatusType.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/dto/ToApplicantDto.java
  src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java
  src/main/java/sync/slamtalk/team/dto/ToTeamMatchingListDto.java
  src/main/java/sync/slamtalk/team/entity/TeamApplicant.java
  src/main/java/sync/slamtalk/team/entity/TeamApplyStatusType.java
  src/main/java/sync/slamtalk/team/entity/TeamMatching.java
  src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
  src/main/java/sync/slamtalk/team/repository/TeamApplicantRepository.java
  src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor, ✨ Feature

#107 #80 유저 마이페이지 사용자의 level 및 팀 매칭 완료 횟수를 보여주는 로직 추가
  src/main/java/sync/slamtalk/common/GlobalRestControllerAdvice.java
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java
  src/main/java/sync/slamtalk/user/dto/UserDetailsInfoResponseDto.java
  src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/test/java/sync/slamtalk/mate/repository/MatePostRepositoryTest.java
Labels: ✨ Feature

#109 #108 refactor : Stomp 메서드 Bearer 인증 타입 설정 추가
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
Labels: 🛠️ Refactor

#111 #110 feat : Naver, Google 소셜 로그인 구현
  src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/sync/slamtalk/security/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/sync/slamtalk/security/oauth2/userinfo/NaverOAuth2UserInfo.java
Labels: ✨ Feature

#112 #99 refactor : 유저 최초 정보수집 enum 으로 받게끔 리팩터링
  src/main/java/sync/slamtalk/user/dto/UserUpdatePositionAndSkillRequestDto.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🛠️ Refactor

#115 #114 날짜 타입 관련 변경 및 팀매칭 삭제 기능 오류 해결
  src/main/java/sync/slamtalk/mate/entity/Participant.java
  src/main/java/sync/slamtalk/mate/entity/SkillLevelType.java
  src/main/java/sync/slamtalk/mate/mapper/MatePostEntityToDtoMapper.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/dto/FromApplicantDto.java
  src/main/java/sync/slamtalk/team/dto/FromTeamFormDTO.java
  src/main/java/sync/slamtalk/team/dto/ToApplicantDto.java
  src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java
  src/main/java/sync/slamtalk/team/entity/TeamApplicant.java
  src/main/java/sync/slamtalk/team/entity/TeamApplyStatusType.java
  src/main/java/sync/slamtalk/team/entity/TeamMatching.java
  src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor

#116 #113 feat : 113 refresh token add field
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/dto/UserDetailsAfterRefreshResponseDto.java
  src/main/java/sync/slamtalk/user/dto/UserDetailsInfoResponseDto.java
  src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/test/java/sync/slamtalk/user/AuthServiceTest.java
Labels: ✨ Feature

#121 #117 API 수정 외
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/common/ApiResponse.java
Labels: 🛠️ Refactor

#122 #119 Refactor/119 oauth
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/sync/slamtalk/swagger/test/Controller.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🛠️ Refactor

#124 #120 feat : 유저 출석 기능 구현
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/entity/UserAttendance.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/repository/UserAttendanceRepository.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: ✨ Feature

#133 #132 채팅리스트 로직 수정
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor

#129 #88,91 s3bucket 이미지 업로드 검증메서드 추가, 이미지 삭제수정
  src/main/java/sync/slamtalk/common/ErrorResponseCode.java
  src/main/java/sync/slamtalk/common/s3bucket/FileUploadController.java
  src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3RepositoryImpl.java
Labels: ⚙️ Setting

#135 #125 feat : 유저 마이페이지 수정 기능
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/UpdateUserDetailInfoRequestDto.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/test/java/sync/slamtalk/mate/repository/MatePostRepositoryTest.java
  src/test/java/sync/slamtalk/user/service/UserServiceTest.java
Labels: ✨ Feature

#136 #134 refactor : 최초회원가입 여부 파라미터에 전달하게끔 리팩터링
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
Labels: 🛠️ Refactor

#142 #141 유저 관련 리프레시 재발급 로직 수정 및 반환 타입 수정
  src/main/java/sync/slamtalk/common/GlobalRestControllerAdvice.java
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/UserDetailsMyInfoResponseDto.java
  src/main/java/sync/slamtalk/user/dto/UserDetailsOtherInfoResponseDto.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/test/java/sync/slamtalk/user/AuthServiceTest.java
  src/test/java/sync/slamtalk/user/service/UserServiceTest.java
Labels: 🛠️ Refactor, ✨ Feature

#143 #141 refactor : 소셜로그인 완료 시 리다이렉트 url 변경
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: 🛠️ Refactor

#145 #144 feat : setUserListChatRoom 메서드 구현
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/test/java/sync/slamtalk/chat/service/ChatServiceImplTest.java
Labels: ✨ Feature

#148 #147 농구장 반환 값 수정
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtSummaryDto.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
Labels: 🛠️ Refactor

#149 #137 chat API 수정
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/Messages.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor

#152 #151 농구장 수정
  src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtErrorResponse.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtRequestDTO.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtResponseDTO.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/service/AdminBasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: 🛠️ Refactor

#154 feat: 관리자 페이지를 위해 Role 추가
  src/main/java/sync/slamtalk/user/dto/UserDetailsMyInfoResponseDto.java
Labels: ✨ Feature

#157 #146 feat: redis 이메일 인증관련 service 메서드 추가
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
Labels: ✨ Feature

#160 #146 회원 탈퇴 기능/ 이메일 검증 기능 구현하기
  build.gradle
  src/main/java/sync/slamtalk/email/EmailConfig.java
  src/main/java/sync/slamtalk/email/EmailController.java
  src/main/java/sync/slamtalk/email/EmailErrorResponseCode.java
  src/main/java/sync/slamtalk/email/EmailService.java
  src/main/java/sync/slamtalk/email/dto/PostMailreq.java
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/sync/slamtalk/user/UserRepository.java
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/request/UpdateUserDetailInfoReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserChangePasswordReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserLoginReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserSignUpReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserUpdateNicknameReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserUpdatePositionAndSkillReq.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsMyInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserLogin.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/entity/UserAttendance.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/RevokeService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java
  src/test/java/sync/slamtalk/chat/service/ChatServiceImplTest.java
  src/test/java/sync/slamtalk/security/oauth2/service/NicknameServiceTest.java
  src/test/java/sync/slamtalk/user/AuthServiceTest.java
  src/test/java/sync/slamtalk/user/service/UserServiceTest.java
Labels: ✨ Feature

#163 #156 댓글 crud
  src/main/java/sync/slamtalk/community/controller/CommentController.java
  src/main/java/sync/slamtalk/community/dto/CommentCreateRequestDTO.java
  src/main/java/sync/slamtalk/community/dto/CommentResponseDTO.java
  src/main/java/sync/slamtalk/community/dto/CommunityErrorResponseCode.java
  src/main/java/sync/slamtalk/community/entity/Comment.java
  src/main/java/sync/slamtalk/community/entity/Community.java
  src/main/java/sync/slamtalk/community/mapper/CommentMapper.java
  src/main/java/sync/slamtalk/community/repository/CommentRepository.java
  src/main/java/sync/slamtalk/community/service/CommentService.java
  src/main/java/sync/slamtalk/community/service/CommunityService.java
Labels: ✨ Feature

#164 #162 refactor : 회원탈퇴시 7일동안 재가입 및 소셜로그인 불가능하게끔 로직 수정
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/sync/slamtalk/user/UserRepository.java
Labels: 🐞 Bug

#170 #165 농구장 이미지 업로드 구현
  src/main/java/sync/slamtalk/community/controller/CommunityController.java
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: ✨ Feature

#167 build.gradle과 .gitignore 변경 및 목록 필터링 기능 구현
  .gitignore
  build.gradle
  src/main/java/sync/slamtalk/common/BaseEntity.java
  src/main/java/sync/slamtalk/mate/controller/MatePostController.java
  src/main/java/sync/slamtalk/mate/dto/FromParticipantDto.java
  src/main/java/sync/slamtalk/mate/dto/MateFormDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostListDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostToDto.java
  src/main/java/sync/slamtalk/mate/dto/MateSearchCondition.java
  src/main/java/sync/slamtalk/mate/dto/PositionListDTO.java
  src/main/java/sync/slamtalk/mate/dto/TestCondition.java
  src/main/java/sync/slamtalk/mate/dto/UnrefinedMatePostDTO.java
  src/main/java/sync/slamtalk/mate/entity/ApplyStatusType.java
  src/main/java/sync/slamtalk/mate/entity/MatePost.java
  src/main/java/sync/slamtalk/mate/entity/Participant.java
  src/main/java/sync/slamtalk/mate/entity/PositionType.java
  src/main/java/sync/slamtalk/mate/entity/Post.java
  src/main/java/sync/slamtalk/mate/entity/SkillLevelList.java
  src/main/java/sync/slamtalk/mate/entity/SkillLevelType.java
  src/main/java/sync/slamtalk/mate/entity/Team.java
  src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java
  src/main/java/sync/slamtalk/mate/mapper/EntityToDtoMapper.java
  src/main/java/sync/slamtalk/mate/mapper/MatePostEntityToDtoMapper.java
  src/main/java/sync/slamtalk/mate/repository/QueryRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/entity/TeamApplicant.java
  src/main/java/sync/slamtalk/team/entity/TeamMatching.java
  src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: ✨ Feature

#173 #158,#166 채팅방 입장 전 로직 유형별 수정, 중복생성과 접속 유형 검증 메서드 추가
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor, ✨ Feature

#175 #174 feat : 팀매칭/상대팀 매칭 게스트 api 추가하기
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
Labels: ✨ Feature

#177 충돌나는 부분 수정
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🐞 Bug

#180 팀매칭 서비스 계층 충돌 해결
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🐞 Bug

#176 #161 게시판 이미지 업로드 검증 로직
  src/main/java/sync/slamtalk/community/entity/CommunityImage.java
  src/main/java/sync/slamtalk/community/service/CommunityService.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
Labels: ✨ Feature

#181 프론트엔드 수정 요청 반영
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/dto/FromTeamFormDTO.java
  src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java
  src/main/java/sync/slamtalk/team/entity/TeamMatching.java
Labels: 🛠️ Refactor

#183 refactor: 로컬 개발용 회원가입 api 추가했습니다
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
Labels: 🛠️ Refactor, ✨ Feature

#184 dto 필드명 수정
  src/main/java/sync/slamtalk/mate/dto/MatePostToDto.java
  src/main/java/sync/slamtalk/mate/mapper/EntityToDtoMapper.java
Labels: 🛠️ Refactor

#186 #178 refactor: securityConfig에 제외 경로 추가
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
Labels: ✨ Feature

#188 dto로 전달하는 필드명 추가 및 변경, api 요청 테스트 확인
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java
  src/main/java/sync/slamtalk/team/entity/TeamMatching.java
  src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor

#190 테스트 를 위한 일부 로직 주석 처리 및 상대팀 매칭 신청자의 CANCELED 조건 변경
  src/main/java/sync/slamtalk/mate/entity/Participant.java
  src/main/java/sync/slamtalk/team/entity/TeamApplicant.java
  src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor

#193 #80 feat : 마이페이지 팀매칭 개수, 상대팀 매칭 개수 구하는 로직 추가
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsMyInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: ✨ Feature

#196 #195 리프레시 토큰 업데이트 하는 로직 및 NPE 뜨던 오류 해결
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
Labels: 🛠️ Refactor, 🐞 Bug

#198 #197 fit : admin 권한 설정 변경
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
Labels: 🐞 Bug

#199 #197 fit : admin 권한 설정 수정
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
Labels: 🐞 Bug

#201 #194 MYP15, MYP16 내가 참석한 팀 매칭 내역, 농구 메이트 내역, 임박한 매칭 전달하기!
  src/main/java/sync/slamtalk/mate/controller/MatePostController.java
  src/main/java/sync/slamtalk/mate/dto/response/MyMateListRes.java
  src/main/java/sync/slamtalk/mate/mapper/EntityToDtoMapper.java
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/dto/response/MyTeamMatchingListRes.java
  src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/response/UserSchedule.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: ✨ Feature

#203 #191 채팅방 중복 생성 방지 로직 추가
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor, 🐞 Bug

#204 #192 채팅방 입장,퇴장 메세지 작업
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/common/BaseEntity.java
Labels: 🛠️ Refactor

#205 #192 refactor : @Transactional추가
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
Labels: 🛠️ Refactor

#206 #194 시간 순으로 배열을 보내주게끔 설계하기
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🛠️ Refactor, ✨ Feature

#207 프론트엔드와 소통을 포함한 기타 수정사항 반영
  src/main/java/sync/slamtalk/mate/dto/UnrefinedMatePostDTO.java
  src/main/java/sync/slamtalk/mate/entity/ApplyStatusType.java
  src/main/java/sync/slamtalk/mate/mapper/EntityToDtoMapper.java
  src/main/java/sync/slamtalk/mate/repository/QueryRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/entity/TeamApplicant.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor

#209 #80 내가 제보한 승인된 농구장 개수 구해서 레벨에 반영하는 로직 추가
  src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsMyInfo.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/main/java/sync/slamtalk/user/utils/UserLevelScore.java
Labels: 🛠️ Refactor, ✨ Feature

#210 #82 채팅방에서 과거 내역 요청
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/test/java/sync/slamtalk/chat/redis/RedisServiceTest.java
  src/test/java/sync/slamtalk/chat/service/ChatServiceImplTest.java
Labels: 🛠️ Refactor, ✨ Feature

#211 #202 제보한 농구장 조회/수정 기능
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtErrorResponse.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtReportResponseDTO.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtReportSummaryDTO.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🛠️ Refactor, ✨ Feature

#213 #212 bug : 채팅방생성에러메세지해결시도
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#215 채팅방 뒤로가기 시 readIndex 업데이트 안되는 문제 해결 시도
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#216 bug : 채팅방나가시 시 readIndex update 안되는 문제 해결 시도
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#217 bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#218 과거 내역 가져오기 메세지 누락 문제 해결 시도
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#219 bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(메세지 저장하는 로직에도 @Transactional 추가)
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#220 bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(메세지 db 저장 시 Redis 에도 저장하게 함)
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#221 bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도(트랜잭션 격리 수준 하향)
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#222 bug : 채팅방 과거 내역 요청 시 메세지 누락 문제 해결 시도
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#227 #212 과거 내역 버그 수정, 과거 내역 요청 횟수 추가
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor, ✨ Feature, 🐞 Bug

#228 #226 refactor : 소셜 로그인 성공 및 실패 시 리다이렉트 url을 프론트 서버 url로 리팩터링
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: 🛠️ Refactor

#230 #229 유저ID 반환
  src/main/java/sync/slamtalk/community/dto/CommunityResponseDTO.java
  src/main/java/sync/slamtalk/community/mapper/CommunityMapper.java
Labels: 🛠️ Refactor

#233 #231 게시글 조회 시, 댓글 같이 조회
  src/main/java/sync/slamtalk/community/controller/CommentController.java
  src/main/java/sync/slamtalk/community/controller/CommunityController.java
  src/main/java/sync/slamtalk/community/dto/CommunityResponseDTO.java
  src/main/java/sync/slamtalk/community/mapper/CommentMapper.java
  src/main/java/sync/slamtalk/community/mapper/CommunityMapper.java
  src/main/java/sync/slamtalk/community/service/CommunityService.java
Labels: 🛠️ Refactor

#235 #231 feat : community 게스트 권한 설정
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
Labels: ✨ Feature

#237 #234 농구장 채팅방 매핑 & 반환
  src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtAdminRequestDTO.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtFullResponseDTO.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: ✨ Feature

#238 #236 농구장 채팅방 생성
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor, ✨ Feature

#242 #232 유저 Level 시스템 관련 게시글 작성 조회 및 Level 임계값 10 으로 설정 및 레벨 초깃값 1로 하기
  src/main/java/sync/slamtalk/community/repository/CommunityRepository.java
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/main/java/sync/slamtalk/user/utils/UserLevelScore.java
Labels: ✨ Feature

#243 #241 Stomp 메세지 컨트롤, chatService refactoring, 채팅방 퇴장 로직 수정
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/RoomCode.java
  src/main/java/sync/slamtalk/chat/config/StompHandler.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/redis/RedisController.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor

#246 메서드 중복 제거
  src/main/java/sync/slamtalk/chat/service/ChatService.java
Labels: 🐞 Bug

#248 #247 과거 내역 요청 에러 수정
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#245 #244 상대방 프로필 보기 게스트 권한 설정
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
Labels: 🛠️ Refactor, ✨ Feature

#251 #250 유저 마이페이지 수정 로직 리팩터링
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🛠️ Refactor

#252 #250 유저 마이페이지 수정 리팩터링
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🛠️ Refactor

#253 #250 bug : user의 값이 null 일때 NPE가 발생하던 오류 수정
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🐞 Bug

#254 #250 유저 마이페이지 수정
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: ✨ Feature

#255 #250 상대방 마이페이지 디버깅용 로직 추가
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: ✨ Feature

#256 #249 사용료, 야간조명, 개방시간, 주차 가능 여부 필드 수정
  src/main/java/sync/slamtalk/map/dto/BasketballCourtAdminRequestDTO.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtFullResponseDTO.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtReportResponseDTO.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtRequestDTO.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtResponseDTO.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/entity/Fee.java
  src/main/java/sync/slamtalk/map/entity/NightLighting.java
  src/main/java/sync/slamtalk/map/entity/OpeningHours.java
  src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: 🛠️ Refactor

#257 #250 feat : 디버깅용 로직 추가
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: ✨ Feature

#258 bug 채팅리스트 조회 에러 원인 분석
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/test/java/sync/slamtalk/chat/redis/RedisServiceTest.java
Labels: 🐞 Bug

#259 bug : 리스트 조회 에러 로그 확인
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#260 bug : 리스트 조회 에러 로그 확인
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#261 #241 채팅 리스트 로직 수정, s3bucket 에 저장가능한 이미지 확장자 추가
  build.gradle
  src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3RepositoryImpl.java
  src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java
Labels: 🛠️ Refactor

#262 #241 채팅방 중복 생성 버그 수정
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug
