Repository SlamTalk/slam-talk-backend, pull requests merged in 2024-01, with the labels that each got.

#3 docs : README.md
  README.md
Labels: 📄 Docs

#12 #10 채팅기능기본설정
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/ChatRoomDTO.java
Labels: ✨ Feature

#14 refactor : annotation 추가
  src/main/java/sync/slamtalk/chat/dto/ChatMessageDTO.java
Labels: 🛠️ Refactor

#19 #18 같이하기 관련 엔터티 생성
  src/main/java/sync/slamtalk/mate/domain/MatePost.java
  src/main/java/sync/slamtalk/mate/domain/Member.java
  src/main/java/sync/slamtalk/mate/domain/Participant.java
Labels: ✨ Feature

#20 #11 메이트 찾기 글쓰기를 위한 Repository, Controller, Service 파일 생성
  src/main/java/sync/slamtalk/mate/controller/RegisterMatePostController.java
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/mate/repository/MemberRepository.java
  src/main/java/sync/slamtalk/mate/repository/ParticipantRepository.java
  src/main/java/sync/slamtalk/mate/service/RegisterMatePostService.java
Labels: ✨ Feature

#22 #21 Swagger 기본 설정 및 의존성 추가
  build.gradle
  src/main/java/sync/slamtalk/swagger/SwaggerConfig.java
  src/main/java/sync/slamtalk/test/Controller.java
Labels: ✨ Feature

#24 #15 채팅방 사용자 검증 로직, 에러 처리 추가
  src/main/java/sync/slamtalk/chat/config/ChatErrorHandler.java
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/ErrorMessage.java
  src/main/java/sync/slamtalk/chat/config/GenericMessage.java
  src/main/java/sync/slamtalk/chat/config/Message.java
  src/main/java/sync/slamtalk/chat/config/RoomCode.java
  src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatMessageDTO.java
  src/main/java/sync/slamtalk/common/ApiResponse.java
  src/main/java/sync/slamtalk/common/BaseException.java
  src/main/java/sync/slamtalk/common/ErrorResponseCode.java
  src/main/java/sync/slamtalk/common/ResponseCode.java
Labels: 🛠️ Refactor, ✨ Feature

#27 #21 Swagger 모듈 개발 - Controller 수정
  src/main/java/sync/slamtalk/test/Controller.java
Labels: 🐞 Bug

#29 #28 refactor: ErrorResponseCode
  src/main/java/sync/slamtalk/common/ApiResponse.java
  src/main/java/sync/slamtalk/common/BaseException.java
  src/main/java/sync/slamtalk/common/ErrorResponseCode.java
  src/main/java/sync/slamtalk/common/ResponseCodeDetails.java
Labels: 🛠️ Refactor

#32 #26 유저 - 엔티티, 레포지토리 생성하기
  build.gradle
  src/main/java/sync/slamtalk/user/UserRepository.java
  src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
  src/main/java/sync/slamtalk/user/entity/SocialType.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/entity/UserBasketballPositionType.java
  src/main/java/sync/slamtalk/user/entity/UserBasketballSkillLevelType.java
  src/main/java/sync/slamtalk/user/entity/UserRole.java
Labels: ✨ Feature

#30 #11 메이트찾기 글쓰기 등록
  src/main/java/sync/slamtalk/mate/controller/RegisterMatePostController.java
  src/main/java/sync/slamtalk/mate/domain/MatePost.java
  src/main/java/sync/slamtalk/mate/domain/User.java
  src/main/java/sync/slamtalk/mate/dto/MateFormDTO.java
  src/main/java/sync/slamtalk/mate/repository/UserRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/RegisterMatePostService.java
Labels: ✨ Feature

#40 #34 채팅서비스 구현, 레포지토리 수정
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/CustomWebSocketHandler.java
  src/main/java/sync/slamtalk/chat/config/RoomCode.java
  src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java
  src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/dto/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/dto/Response/ChatUserDTO.java
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/Messages.java
  src/main/java/sync/slamtalk/chat/entity/RoomAction.java
  src/main/java/sync/slamtalk/chat/entity/RoomType.java
  src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
Labels: 🛠️ Refactor, ✨ Feature

#43 #36 #39 리팩토링, 메이트찾기 글 조회, 삭제, 수정 기능 추가
  build.gradle
  src/main/java/sync/slamtalk/mate/controller/MatepostController.java
  src/main/java/sync/slamtalk/mate/controller/RegisterMatePostController.java
  src/main/java/sync/slamtalk/mate/domain/Participant.java
  src/main/java/sync/slamtalk/mate/domain/User.java
  src/main/java/sync/slamtalk/mate/dto/MateFormDTO.java
  src/main/java/sync/slamtalk/mate/entity/ApplyStatusType.java
  src/main/java/sync/slamtalk/mate/entity/MatePost.java
  src/main/java/sync/slamtalk/mate/entity/Participant.java
  src/main/java/sync/slamtalk/mate/entity/PositionType.java
  src/main/java/sync/slamtalk/mate/entity/RecruitmentStatusType.java
  src/main/java/sync/slamtalk/mate/entity/SkillLevelType.java
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/mate/repository/ParticipantRepository.java
  src/main/java/sync/slamtalk/mate/repository/UserRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
Labels: 🛠️ Refactor, ✨ Feature

#41 #13 근처 농구장 마커 표시 & 클릭시 해당 시설 정보 표시
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtErrorResponse.java
  src/main/java/sync/slamtalk/map/entity/AdminStatus.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
Labels: ✨ Feature

#48 #26 유저 모듈 개발
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/sync/slamtalk/security/config/CorsConfig.java
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
  src/main/java/sync/slamtalk/security/dto/JwtTokenResponseDto.java
  src/main/java/sync/slamtalk/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/sync/slamtalk/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/sync/slamtalk/security/jwt/JwtFilter.java
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/security/service/CustomUserDetailsService.java
  src/main/java/sync/slamtalk/security/utils/CookieUtil.java
  src/main/java/sync/slamtalk/swagger/test/Controller.java
  src/main/java/sync/slamtalk/user/UserRepository.java
  src/main/java/sync/slamtalk/user/UserService.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/UserLoginRequestDto.java
  src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
Labels: ✨ Feature

#50 #49 AccessToken 헤더로 받게끔 설정, RefreshToken 쿠키로 받게끔 설정하기
  src/main/java/sync/slamtalk/security/config/CorsConfig.java
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
  src/main/java/sync/slamtalk/security/dto/JwtTokenResponseDto.java
  src/main/java/sync/slamtalk/security/jwt/JwtFilter.java
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/security/utils/CookieUtil.java
  src/main/java/sync/slamtalk/user/UserController.java
  src/main/java/sync/slamtalk/user/UserService.java
Labels: ✨ Feature

#51 #42 제보 받은 농구장 정보 저장
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: ✨ Feature

#53 #52 refactor 웹소켓 STOMP 사용시 accessToken에서 userId 추출하는 메서드 리팩토링
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
Labels: 🛠️ Refactor

#54 #44 채팅리스트 요구사항 서비스,컨트롤러 작성 외
  build.gradle
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/CustomWebSocketHandler.java
  src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java
  src/main/java/sync/slamtalk/chat/config/StompWebSocketConfig.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/ChatErrorResponseCode.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/entity/Messages.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/UserMock.java
  src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserMockRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/test/java/sync/slamtalk/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/sync/slamtalk/chat/repository/MessagesRepositoryTest.java
Labels: 🛠️ Refactor, ✨ Feature

#58 #47 메이트 찾기,신청자 목록 관련 리팩토링 및 기능 추가
  src/main/java/sync/slamtalk/mate/controller/MatePostController.java
  src/main/java/sync/slamtalk/mate/controller/ParticipantController.java
  src/main/java/sync/slamtalk/mate/dto/MateFormDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostApplicantDTO.java
  src/main/java/sync/slamtalk/mate/entity/MatePost.java
  src/main/java/sync/slamtalk/mate/entity/Participant.java
  src/main/java/sync/slamtalk/mate/entity/PositionType.java
  src/main/java/sync/slamtalk/mate/entity/RecruitedSkillLevelType.java
  src/main/java/sync/slamtalk/mate/entity/SkillLevelType.java
  src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
Labels: 🛠️ Refactor, ✨ Feature

#60 #55 usermock Entity -> user Entity 수정에 따른 연관관계 매핑, 서비스 수정
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/CustomWebSocketHandler.java
  src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java
  src/main/java/sync/slamtalk/chat/config/StompHandler.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/controller/StompChatController.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatCreateDTO.java
  src/main/java/sync/slamtalk/chat/dto/Request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/Response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/entity/UserMock.java
  src/main/java/sync/slamtalk/chat/repository/ChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/repository/UserMockRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/test/java/sync/slamtalk/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java
Labels: 🛠️ Refactor

#62 #57 농구장 테이블 필드 추가 및 수정
  src/main/java/sync/slamtalk/map/dto/BasketballCourtDto.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
Labels: 🛠️ Refactor

#67 #66 bug : cors 에러 수정
  src/main/java/sync/slamtalk/security/config/CorsConfig.java
Labels: 🐞 Bug

#65 #64 modified : BaseEntity
  src/main/java/sync/slamtalk/common/BaseEntity.java
Labels: 🛠️ Refactor

#69 #6 #56 Feature 소셜 로그인 기능 추가 및 토큰 저장 방식 리팩터링
  src/main/java/sync/slamtalk/SlamtalkApplication.java
  src/main/java/sync/slamtalk/security/config/CorsConfig.java
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
  src/main/java/sync/slamtalk/security/dto/JwtTokenDto.java
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/security/logout/CustomLogoutHandler.java
  src/main/java/sync/slamtalk/security/oauth2/CustomOAuth2User.java
  src/main/java/sync/slamtalk/security/oauth2/OAuthAttributes.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/sync/slamtalk/security/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/sync/slamtalk/security/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/sync/slamtalk/security/oauth2/userinfo/NaverOAuth2UserInfo.java
  src/main/java/sync/slamtalk/security/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/sync/slamtalk/security/utils/CookieUtil.java
  src/main/java/sync/slamtalk/swagger/test/Controller.java
  src/main/java/sync/slamtalk/user/UserController.java
  src/main/java/sync/slamtalk/user/UserRepository.java
  src/main/java/sync/slamtalk/user/UserService.java
  src/main/java/sync/slamtalk/user/dto/UserLoginRequestDto.java
  src/main/java/sync/slamtalk/user/dto/UserLoginResponseDto.java
  src/main/java/sync/slamtalk/user/dto/UserSignUpRequestDto.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/test/java/sync/slamtalk/user/UserServiceTest.java
Labels: 🛠️ Refactor, ✨ Feature

#71 #70 refactor : github-acionts 수정
  .github/workflows/gradle.yml
Labels: 🛠️ Refactor

#73 #72 refactor : bug 수정 Transaction 어노테이션 추가
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
Labels: 🛠️ Refactor, 🐞 Bug

#76 #75 Refactor jwt filter
  src/main/java/sync/slamtalk/security/jwt/JwtFilter.java
Labels: 🛠️ Refactor

#74 #63 관리자 제보 목록 조회 및 수락 기능 추가
  src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
  src/main/java/sync/slamtalk/map/service/AdminBasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: ✨ Feature

#77 #68 Redis 설정파일 작성, 리팩토링
  build.gradle
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/config/StompErrorHandler.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/entity/Messages.java
  src/main/java/sync/slamtalk/chat/redis/RedisConfig.java
  src/main/java/sync/slamtalk/chat/redis/RedisController.java
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/common/BaseEntity.java
  src/test/java/sync/slamtalk/chat/redis/RedisServiceTest.java
  src/test/java/sync/slamtalk/chat/repository/UserChatRoomRepositoryTest.java
Labels: ⚙️ Setting, 🛠️ Refactor

#81 #45 채팅퇴장/뒤로가기 서비스,컨트롤러 작성
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/controller/ChatController.java
  src/main/java/sync/slamtalk/chat/redis/RedisController.java
  src/main/java/sync/slamtalk/chat/repository/MessagesRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/common/BaseEntity.java
Labels: ✨ Feature

#87 #84 s3bucket 연동
  build.gradle
  src/main/java/sync/slamtalk/common/ErrorResponseCode.java
  src/main/java/sync/slamtalk/common/s3bucket/FileUploadController.java
  src/main/java/sync/slamtalk/common/s3bucket/config/CommonUtils.java
  src/main/java/sync/slamtalk/common/s3bucket/config/S3Config.java
  src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3Repository.java
  src/main/java/sync/slamtalk/common/s3bucket/repository/AwsS3RepositoryImpl.java
Labels: ⚙️ Setting

#85 #61 메이트찾기 목록 및 dto 생성
  src/main/java/sync/slamtalk/mate/controller/MatePostController.java
  src/main/java/sync/slamtalk/mate/dto/MateFormDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostApplicantDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostListDTO.java
  src/main/java/sync/slamtalk/mate/dto/PositionListDTO.java
  src/main/java/sync/slamtalk/mate/entity/MatePost.java
  src/main/java/sync/slamtalk/mate/entity/Participant.java
  src/main/java/sync/slamtalk/mate/mapper/MatePostEntityToDtoMapper.java
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
  src/main/java/sync/slamtalk/user/UserRepository.java
Labels: ✨ Feature

#90 #89 Map 게스트 Swagger Tag 추가
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
Labels: 🛠️ Refactor

#93 #92 refactor 카카오 로그인 성공시 응답 url 수정
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: 🛠️ Refactor

#94 #80 유저 마이페이지 기능 구현(미완성)
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/controller/UserController.java
  src/main/java/sync/slamtalk/user/dto/UserDetailsInfoResponseDto.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
  src/test/java/sync/slamtalk/user/AuthServiceTest.java
Labels: ✨ Feature

#96 #86 팀 매칭 게시글 CRUD 구현 및 메이트 찾기 리팩토링
  build.gradle
  src/main/java/sync/slamtalk/mate/controller/ParticipantController.java
  src/main/java/sync/slamtalk/mate/dto/MateFormDTO.java
  src/main/java/sync/slamtalk/mate/dto/MatePostDTO.java
  src/main/java/sync/slamtalk/mate/entity/MatePost.java
  src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java
  src/main/java/sync/slamtalk/mate/mapper/MatePostEntityToDtoMapper.java
  src/main/java/sync/slamtalk/mate/repository/MatePostRepository.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/dto/FromTeamFormDTO.java
  src/main/java/sync/slamtalk/team/dto/ToTeamFormDTO.java
  src/main/java/sync/slamtalk/team/entity/TeamMatchings.java
  src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
  src/main/java/sync/slamtalk/team/repository/TeamMatchingRepository.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor, ✨ Feature

#98 #97 UserLoginResponseDto 반환 값 추가
  src/main/java/sync/slamtalk/user/dto/UserLoginResponseDto.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
Labels: 🛠️ Refactor

#101 #100 Map 게스트 기능을 위한 엔드포인트 수정
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
Labels: 🛠️ Refactor

#102 #89 #100 시큐리티필터링에 게스트 해당 url 추가하는 설정
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
Labels: ✨ Feature
