Repository SlamTalk/slam-talk-backend, pull requests merged in 2024-05, with the labels that each got.

#283 #270 농구장 리팩토링
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/entity/Fee.java
  src/main/java/sync/slamtalk/map/entity/NightLighting.java
  src/main/java/sync/slamtalk/map/entity/OpeningHours.java
  src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
  src/main/java/sync/slamtalk/map/entity/RegistrationStatus.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
  src/main/java/sync/slamtalk/map/service/AdminBasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🛠️ Refactor

#311 Develop->main
  src/main/java/sync/slamtalk/chat/entity/ChatRoom.java
  src/main/java/sync/slamtalk/common/ErrorResponseCode.java
  src/main/java/sync/slamtalk/map/controller/AdminBasketballCourtController.java
  src/main/java/sync/slamtalk/map/controller/BasketballCourtController.java
  src/main/java/sync/slamtalk/map/entity/BasketballCourt.java
  src/main/java/sync/slamtalk/map/entity/Fee.java
  src/main/java/sync/slamtalk/map/entity/NightLighting.java
  src/main/java/sync/slamtalk/map/entity/OpeningHours.java
  src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
  src/main/java/sync/slamtalk/map/entity/RegistrationStatus.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/map/repository/BasketballCourtRepository.java
  src/main/java/sync/slamtalk/map/service/AdminBasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/BasketballCourtService.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
  src/main/java/sync/slamtalk/notification/NotificationController.java
  src/main/java/sync/slamtalk/notification/NotificationRepository.java
  src/main/java/sync/slamtalk/notification/NotificationSender.java
  src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepository.java
  src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java
  src/main/java/sync/slamtalk/notification/dto/request/NotificationRequest.java
  src/main/java/sync/slamtalk/notification/dto/response/NotificationResponse.java
  src/main/java/sync/slamtalk/notification/model/Notification.java
  src/main/java/sync/slamtalk/notification/model/NotificationContent.java
  src/main/java/sync/slamtalk/notification/service/InAppNotificationSender.java
  src/main/java/sync/slamtalk/notification/service/NotificationService.java
  src/main/java/sync/slamtalk/notification/util/StringSlicer.java
  src/main/java/sync/slamtalk/user/service/UserService.java
Labels: 🌏 Deploy

#313 채팅방 새로운 메세지 알림 외
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/dto/request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/notification/model/NotificationContent.java
Labels: 🛠️ Refactor, ✨ Feature, 🐞 Bug

#312 농구장 등록 시 채팅방 자동 생성 및 매핑
  src/main/java/sync/slamtalk/map/dto/BasketballCourtErrorResponse.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: ✨ Feature

#314 Develop->main
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/dto/request/ChatMessageDTO.java
  src/main/java/sync/slamtalk/chat/dto/response/ChatRoomDTO.java
  src/main/java/sync/slamtalk/chat/service/ChatService.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/map/dto/BasketballCourtErrorResponse.java
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
  src/main/java/sync/slamtalk/notification/model/NotificationContent.java
Labels: 🌏 Deploy

#318 #317 농구장 정보 반환 값 수정
  src/main/java/sync/slamtalk/map/entity/EnumType.java
  src/main/java/sync/slamtalk/map/entity/Fee.java
  src/main/java/sync/slamtalk/map/entity/NightLighting.java
  src/main/java/sync/slamtalk/map/entity/OpeningHours.java
  src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
Labels: ✨ Feature

#319 #307 email package 정리하기
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/email/EmailController.java
  src/main/java/sync/slamtalk/email/EmailErrorResponseCode.java
  src/main/java/sync/slamtalk/email/EmailService.java
  src/main/java/sync/slamtalk/email/dto/PostMailReq.java
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
  src/main/java/sync/slamtalk/security/service/CustomUserDetailsService.java
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/dto/request/UserChangePasswordReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserTmpPasswordReq.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/utils/PasswordGenerator.java
  src/main/resources/templates/password-reset-template.html
Labels: 🛠️ Refactor, ✨ Feature

#320 develop -> main merge
  src/main/java/sync/slamtalk/chat/redis/RedisService.java
  src/main/java/sync/slamtalk/email/EmailController.java
  src/main/java/sync/slamtalk/email/EmailErrorResponseCode.java
  src/main/java/sync/slamtalk/email/EmailService.java
  src/main/java/sync/slamtalk/email/dto/PostMailReq.java
  src/main/java/sync/slamtalk/map/entity/EnumType.java
  src/main/java/sync/slamtalk/map/entity/Fee.java
  src/main/java/sync/slamtalk/map/entity/NightLighting.java
  src/main/java/sync/slamtalk/map/entity/OpeningHours.java
  src/main/java/sync/slamtalk/map/entity/ParkingAvailable.java
  src/main/java/sync/slamtalk/map/mapper/BasketballCourtMapper.java
  src/main/java/sync/slamtalk/security/config/SecurityConfig.java
  src/main/java/sync/slamtalk/security/service/CustomUserDetailsService.java
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/dto/request/UserChangePasswordReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserTmpPasswordReq.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/utils/PasswordGenerator.java
  src/main/resources/templates/password-reset-template.html
Labels: 🛠️ Refactor, 🌏 Deploy

#326 메세지 생성 알림 내 uri, 알림 삭제 호출 시기 변경
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/service/ChatNotificationServiceImpl.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java
Labels: 🛠️ Refactor, 🐞 Bug

#327 Develop->main
  src/main/java/sync/slamtalk/chat/config/ChatInboundInterceptor.java
  src/main/java/sync/slamtalk/chat/service/ChatNotificationServiceImpl.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java
Labels: 🌏 Deploy

#328 fix : 알림 메세지 수정
  src/main/java/sync/slamtalk/chat/service/ChatNotificationServiceImpl.java
Labels: 🐞 Bug

#329 Develop->main
  src/main/java/sync/slamtalk/chat/service/ChatNotificationServiceImpl.java
Labels: 🌏 Deploy

#330 fix : userName은 무엇인가..userNickName 으로 변경
  src/main/java/sync/slamtalk/chat/service/MessageService.java
Labels: 🐞 Bug

#331 Develop->main
  src/main/java/sync/slamtalk/chat/service/MessageService.java
Labels: 🌏 Deploy

#332 #316 게시글 목록에 댓글 개수 포함
  src/main/java/sync/slamtalk/community/dto/CommunityResponseDTO.java
  src/main/java/sync/slamtalk/community/mapper/CommunityMapper.java
  src/main/java/sync/slamtalk/community/repository/CommentRepository.java
  src/main/java/sync/slamtalk/community/service/CommunityService.java
Labels: ✨ Feature

#333 #324 회원 탈퇴 구현
  src/main/java/sync/slamtalk/security/config/SecurityConstants.java
  src/main/java/sync/slamtalk/security/jwt/JwtFilter.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/sync/slamtalk/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/sync/slamtalk/user/controller/AuthController.java
  src/main/java/sync/slamtalk/user/dto/response/UserDetailsOtherInfo.java
  src/main/java/sync/slamtalk/user/entity/SocialType.java
  src/main/java/sync/slamtalk/user/entity/User.java
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
  src/main/java/sync/slamtalk/user/service/NicknameService.java
  src/main/java/sync/slamtalk/user/service/RevokeSocialLoginService.java
  src/test/java/sync/slamtalk/security/oauth2/service/NicknameServiceTest.java
Labels: 🛠️ Refactor, ✨ Feature

#334 #324 비밀번호 정규표현식으로 인한 에러 수정
  src/main/java/sync/slamtalk/user/dto/request/UserChangePasswordReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserLoginReq.java
  src/main/java/sync/slamtalk/user/dto/request/UserSignUpReq.java
Labels: 🐞 Bug

#338 #337 소셜 로그인은 비밀번호 변경 지원 안함.
  src/main/java/sync/slamtalk/user/error/UserErrorResponseCode.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
Labels: 🛠️ Refactor

#341 #340 임시 비밀번호 발급 api 버그 수정
  src/main/java/sync/slamtalk/user/service/AuthService.java
Labels: 🐞 Bug

#345 #343 농구장 알림 기능
  src/main/java/sync/slamtalk/map/service/ReportBasketballCourtService.java
Labels: ✨ Feature

#346 #344 게시글 댓글 알림 기능
  src/main/java/sync/slamtalk/community/service/CommentService.java
Labels: ✨ Feature

#348 #296 [팀모집/ 상대팀모집] 1차요구사항 반영
  src/main/java/sync/slamtalk/mate/dto/response/MatePostKeyInformation.java
  src/main/java/sync/slamtalk/mate/dto/response/MyMateListRes.java
  src/main/java/sync/slamtalk/mate/entity/MatePost.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/controller/TeamMatchingController.java
  src/main/java/sync/slamtalk/team/dto/response/MyTeamMatchingListRes.java
  src/main/java/sync/slamtalk/team/dto/response/TeamMatchingKeyInformation.java
  src/main/java/sync/slamtalk/team/entity/TeamMatching.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor

#350 #296 Mate 관련 알림 요구사항 반영
  src/main/java/sync/slamtalk/common/Site.java
  src/main/java/sync/slamtalk/mate/event/CompleteMateEvent.java
  src/main/java/sync/slamtalk/mate/event/MatePostPostDeletionEvent.java
  src/main/java/sync/slamtalk/mate/event/MateSupportAcceptanceEvent.java
  src/main/java/sync/slamtalk/mate/event/MateSupportEvent.java
  src/main/java/sync/slamtalk/mate/service/MateDeclineEvent.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
  src/main/java/sync/slamtalk/notification/listener/mate/CompleteMatePostNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostDeleteNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostRejectSupportNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportAcceptanceNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportNotifier.java
Labels: 🛠️ Refactor, ✨ Feature

#352 #296 [메이트 매칭] 지원 취소 -> 지원 거절 시 지원자에게 알림 가도록 수정
  src/main/java/sync/slamtalk/mate/event/MateDeclineEvent.java
  src/main/java/sync/slamtalk/mate/service/ParticipantService.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostDeleteNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostRejectSupportNotifier.java
Labels: 🛠️ Refactor, 🐞 Bug

#353 #296 팀매칭 알림 요구사항 구현
  src/main/java/sync/slamtalk/common/Site.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/notification/listener/team/CompleteTeamMachingNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingDeleteNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingRejectSupportNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportAcceptanceNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportNotifier.java
  src/main/java/sync/slamtalk/notification/model/NotificationType.java
  src/main/java/sync/slamtalk/team/event/CompleteTeamMatchingEvent.java
  src/main/java/sync/slamtalk/team/event/TeamMatchingPostDeletionEvent.java
  src/main/java/sync/slamtalk/team/event/TeamMatchingSupportAcceptanceEvent.java
  src/main/java/sync/slamtalk/team/event/TeamMatchingSupportEvent.java
  src/main/java/sync/slamtalk/team/event/TeamMatchingSupportRejectionEvent.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor, ✨ Feature

#356 # [팀매칭/메이트매칭] 알림 메세지 format 바꾸기
  src/main/java/sync/slamtalk/notification/listener/mate/CompleteMatePostNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostDeleteNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostRejectSupportNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportAcceptanceNotifier.java
  src/main/java/sync/slamtalk/notification/listener/mate/MatePostSupportNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/CompleteTeamMachingNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingDeleteNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingRejectSupportNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportAcceptanceNotifier.java
  src/main/java/sync/slamtalk/notification/listener/team/TeamMatchingSupportNotifier.java
Labels: 🛠️ Refactor

#358 [SMTP관련] 이메일 인증, 임시 비밀번호 발급 템플릿 css 변경
  src/main/resources/templates/password-reset-template.html
  src/main/resources/templates/register-email-verification-template.html
Labels: 🛠️ Refactor

#360 Bug/355 chat
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java
  src/main/java/sync/slamtalk/notification/model/Notification.java
  src/main/java/sync/slamtalk/notification/service/NotificationService.java
Labels: 🐞 Bug

#361 Develop->main
  src/main/java/sync/slamtalk/chat/entity/UserChatRoom.java
  src/main/java/sync/slamtalk/chat/repository/UserChatRoomRepository.java
  src/main/java/sync/slamtalk/chat/service/ChatServiceImpl.java
  src/main/java/sync/slamtalk/notification/custom/CustomNotificationRepositoryImpl.java
  src/main/java/sync/slamtalk/notification/model/Notification.java
  src/main/java/sync/slamtalk/notification/service/NotificationService.java
Labels: 🌏 Deploy

#362 fix : 알림 url 수정
  src/main/java/sync/slamtalk/chat/service/MessageService.java
Labels: 🛠️ Refactor

#363 Develop->main
  src/main/java/sync/slamtalk/chat/service/MessageService.java
Labels: 🌏 Deploy

#365 [로그인 버그] 동시접속 가능하게 끔 하는 로직
  src/main/java/sync/slamtalk/security/jwt/JwtTokenProvider.java
  src/main/java/sync/slamtalk/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/sync/slamtalk/user/service/AuthService.java
Labels: 🐞 Bug

#368 [팀매칭/상대팀매칭] 약속시간 검증로직 추가
  src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🛠️ Refactor

#370 [팀매칭/상대팀매칭] 게시글 시간 검증 로직 추가
  src/main/java/sync/slamtalk/mate/error/MateErrorResponseCode.java
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/error/TeamErrorResponseCode.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🐞 Bug

#372 [팀매칭/메이트매칭] 게시글 시간 검증 로직 수정
  src/main/java/sync/slamtalk/mate/service/MatePostService.java
  src/main/java/sync/slamtalk/team/service/TeamMatchingService.java
Labels: 🐞 Bug

#375 로그아웃 시 모든 계정이 로그아웃 되는 경우가 발생되는 버그 수정
  src/main/java/sync/slamtalk/security/logout/CustomLogoutHandler.java
Labels: 🐞 Bug
